name: platzi_trips
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  generic_bloc_provider: ^1.0.9
  firebase_auth:
  google_sign_in:
  firebase_storage: ^2.1.0
  cloud_firestore: ^0.9.13
  image_picker: ^0.5.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf


